config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/about'

  get 'Welcome/Contact_page'

  root to: 'welcome#index'
end
  

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def ContactPage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_name
    return 'Omri Hamo Raber'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path%></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Follow me", "https://www.facebook.com/trybloc", class: "social-btn" %></li>
    </ul>      

    <%= yield %>
  </div>  
</body>
</html>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: <%= my_name %></p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Bloccit</h1>
<p>This is the home page for Bloccit.</p>